Repository RedRoverSchool/JenkinsQA_Java_2025_spring, pull requests merged in 2025-05, with the labels that each got.

#1666 ID: RF_01.001.14 |NewItemCreate3Test > testCreateNewItemWithCorrectName
  src/test/java/school/redrover/NewItemCreate3Test.java
Labels: POM

#1670 RF_08.001 | Sign in/out > Sign in
  src/test/java/school/redrover/LogOutTest.java
  src/test/java/school/redrover/NewItemPage2Test.java
  src/test/java/school/redrover/SignInTest.java
  src/test/java/school/redrover/User2Test.java
  src/test/java/school/redrover/page/HomePage.java
  src/test/java/school/redrover/page/freestyle/FreestyleConfigurationPage.java
  src/test/java/school/redrover/page/signIn/SignInPage.java
  src/test/java/school/redrover/page/user/UsersPage.java
Labels: POM

#1660 https://github.com/RedRoverSchool/JenkinsQA_Java_2025_spring/issues/1653
  src/test/java/school/redrover/DashboardViewTest.java
  src/test/java/school/redrover/page/view/NewViewPage.java
Labels: Error

#1725 RF_01.001.02 | Pipeline1Test > Remove duplicate and old classes
  src/test/java/school/redrover/GoToTabBuildHistoryTest.java
  src/test/java/school/redrover/JenkinsVersionTest.java
  src/test/java/school/redrover/MandatoryFieldTest.java
  src/test/java/school/redrover/Pipeline1Test.java
Labels: RF

#1641 TC_12.007.01 | Dashboard with the items > Customize Job Display > Create new List View
  src/test/java/school/redrover/DashboardViewTest.java
  src/test/java/school/redrover/page/HomePage.java
  src/test/java/school/redrover/page/view/EditViewPage.java
Labels: TC

#1687 RF_03.001-002 | PipelineConfigurationPageTest refactor
  src/test/java/school/redrover/DashboardViewTest.java
  src/test/java/school/redrover/FreestyleProjectManagementBuildNowTest.java
  src/test/java/school/redrover/NewItemPage2Test.java
  src/test/java/school/redrover/PipelineConfigurationPageTest.java
  src/test/java/school/redrover/PipelineConfigurationProjectTest.java
  src/test/java/school/redrover/PipelineConfigurePage2Test.java
  src/test/java/school/redrover/PipelineConfigurePage3Test.java
  src/test/java/school/redrover/PipelineConfigurePageTest.java
  src/test/java/school/redrover/page/HomePage.java
  src/test/java/school/redrover/page/pipeline/PipelineConfigurationPage.java
  src/test/java/school/redrover/page/pipeline/PipelineProjectPage.java
Labels: RF, POM

#1734 RF_15.001.1 | User > CRUD user
  src/test/java/school/redrover/LoginTest.java
  src/test/java/school/redrover/NewUserTest.java
  src/test/java/school/redrover/SignInTest.java
  src/test/java/school/redrover/User1Test.java
  src/test/java/school/redrover/User2Test.java
  src/test/java/school/redrover/User4Test.java
  src/test/java/school/redrover/UserTest.java
  src/test/java/school/redrover/UsernameFieldTest.java
  src/test/java/school/redrover/page/user/CreateUserPage.java
  src/test/java/school/redrover/page/user/UsersPage.java
Labels: RF

#1748 RF_10.019.01 | DisplaySystemInfoTest > refactoring and changing tests to POM
  src/test/java/school/redrover/DisplaySystemInfoTest.java
  src/test/java/school/redrover/page/managejenkins/ManageJenkinsPage.java
  src/test/java/school/redrover/page/systeminfo/SystemInfoPage.java
Labels: RF, POM

#1938 AT_10.019.02 | Manage Jenkins > Display System information > Review memory usage data
  src/test/java/school/redrover/DisplaySystemInfoTest.java
  src/test/java/school/redrover/MultibranchPipelineTest.java
  src/test/java/school/redrover/page/systeminfo/SystemInfoPage.java
Labels: POM

#1985 RF_001.01.14 | NewItemPage>selectFolderAndClickOk #1984
  src/test/java/school/redrover/page/newitem/NewItemPage.java
Labels: RF

#2033 AC_05.004.ZZ | Folder Configuration > Save or Apply> Test Apply button in Folder configuration
  src/test/java/school/redrover/FolderTest.java
  src/test/java/school/redrover/page/folder/FolderConfigurationPage.java
Labels: POM
