Repository RedRoverSchool/JenkinsQA_Java_2025_spring, pull requests merged in 2025-04, with the labels that each got.

#614 [Framework] Implement theme reset between tests
  src/test/java/school/redrover/common/JenkinsUtils.java
Labels: enhancement

#1011 RF_10.023.03 | Manage Jenkins > Check About Jenkins | Users should be able to review the list of dependencies used in the Jenkins installation.
  src/test/java/school/redrover/ManageJenkinsTabTest.java
Labels: RF

#1055 AT_10.023.04| Manage Jenkins > Check About Jenkins | Information about static resources should be visible to the user.
  src/test/java/school/redrover/ManageJenkinsTabTest.java
Labels: TC

#1080 TC_03.002.01 | Pipeline Configuration > Project Description >Verify t…
  src/test/java/school/redrover/PipelineConfigurationProjectTest.java
Labels: TC

#1084 Add TC_03.001.05.2
  src/test/java/school/redrover/PipelineConfigurePage2Test.java
Labels: TC

#1113 RF_03.002.01 | Pipeline Configuration > Project Description >Verify t…
  src/test/java/school/redrover/PipelineConfigurationProjectTest.java
Labels: RF

#1169 AT_01.001.58 | New Item > Creatе a new item > The item name input field should accept alphanumeric and special characters
  src/test/java/school/redrover/NewItem5Test.java
Labels: TC

#1189 fix ER_18.006.02 FreestyleProjectManagementBuildNowTest -> testAvailableBuildNowOnbreadcrumbs()
  src/test/java/school/redrover/FreestyleProjectManagementBuildNowTest.java
Labels: ET

#1203 Fix ER_18.006.03 FreestyleProjectManagementBuildNowTest -> testAvailableSuccesResult
  src/test/java/school/redrover/FreestyleProjectManagementBuildNowTest.java
Labels: Error

#1206 RF_ER_03.002.01 PipelineConfigurationProjectTest -> testPreviewAndHidePreviewButtons
  src/test/java/school/redrover/PipelineConfigurationProjectTest.java
Labels: Error

#1331 RF_03.002.02 |Pipeline Configuration > Project Description > Create a project with a description
  src/test/java/school/redrover/PipelineTest.java
Labels: POM

#1333 Refactoring TC_03.001.05 | Pipeline Configuration > Enable or Disable the Project > The warning message is hidden if Project is enabled
  src/test/java/school/redrover/PipelineConfigurePageTest.java
Labels: RF

#1347 RF_01.004.06 | New Item > Folder > Verify a new folder is empty by default
  src/test/java/school/redrover/Folder2Test.java
  src/test/java/school/redrover/NewItem6Test.java
  src/test/java/school/redrover/OrganizationFolderTest.java
  src/test/java/school/redrover/page/FolderProjectPage.java
  src/test/java/school/redrover/page/NewItemPage.java
Labels: POM

#1351 RF_01.004.04 | New Item > Folder > Verify that duplicate item names are not allowed within the same folder
  src/test/java/school/redrover/Folder2Test.java
  src/test/java/school/redrover/NewItem6Test.java
  src/test/java/school/redrover/OrganizationFolderTest.java
  src/test/java/school/redrover/page/NewItemWithinFolderPage.java
  src/test/java/school/redrover/page/OrganizationFolderPage.java
Labels: POM

#1435 RF_03.002.03 |Pipeline Configuration > Project Description > Create a project with a description #1434
  src/test/java/school/redrover/PipelineTest.java
Labels: RF

#1442 TC_23.003_02 | Organization Folder Management > Add new Item > Create new Organization Folder
  src/test/java/school/redrover/OrganizationFolderTest.java
  src/test/java/school/redrover/page/NewItemPage.java
  src/test/java/school/redrover/page/OrganizationFolderConfigurePage.java
  src/test/java/school/redrover/page/OrganizationFolderPage.java
Labels: TC, POM

#1461 TC_03.001.13|Pipeline Configuration > Enable or Disable the Project > Verify Disable Functionality for Pipeline Project
  src/test/java/school/redrover/PipelineTest.java
Labels: POM

#1493 RF_03.001.13|PipelineTest > testCreatePipeline > testDisableProject
  src/test/java/school/redrover/PipelineProjectTest.java
Labels: RF

#1506 RF_02.002.01 > FreestyleProjectTest > testCreateWithDescription
  src/test/java/school/redrover/Description2Test.java
  src/test/java/school/redrover/FreestyleProjectTest.java
  src/test/java/school/redrover/page/freestyle/FreestyleProjectPage.java
Labels: RF, POM

#1513 RF_01.001.58 | NewItem5Test > testCreateItemNameWithSafeCharacters
  src/test/java/school/redrover/NewItem5Test.java
  src/test/java/school/redrover/page/newitem/NewItemPage.java
  src/test/java/school/redrover/testdata/TestDataProvider.java
Labels: RF, POM

#1522 RF_03.001.01 | PipelineDisableTest > disablePipelineTest >Removing duplicate class and test
  src/test/java/school/redrover/PipelineDisableTest.java
Labels: RF

#1529 TC_03.001.14 | Pipeline Configuration > Enable or Disable the Project > Verify that enabling the project pipeline switch works correctly
  src/test/java/school/redrover/PipelineProjectTest.java
Labels: POM

#1540 RF_03.001.14 | PipelineProjectTest >testCreatePipeline > testDisableProject
  src/test/java/school/redrover/PipelineProjectTest.java
Labels: RF

#1587 TC_18.001 | Freestyle Project Management > Access to the Project from the Dashboard > Project Management page is accessible from the Dashboard
  src/test/java/school/redrover/FreestyleProjectTest.java
  src/test/java/school/redrover/page/HomePage.java
  src/test/java/school/redrover/page/freestyle/FreestyleConfigurationPage.java
Labels: TC, POM

#1634 RF_01.001.01 | FooterTest > NodeTest > TrialTest > Removing old unnecessary classes
  src/test/java/school/redrover/FooterTest.java
  src/test/java/school/redrover/NodeTest.java
  src/test/java/school/redrover/TrialTest.java
Labels: RF
